### PR TITLE
Removes call to observer when adding observer.

### PR DESCRIPTION
**Pull request by drdaz**
When adding an observer to a characteristic, the block was called. This is somewhat unexpected. So I've removed the call.

### CODE REVIEW

**Comment by KingOfBrian** [comment]
Hey @drdaz ,
   That is actually intended. The point is that if CoreBluetooth happens to have a cached value, it should get it to the application layer as soon as possible. The next notify may not happen for a while even though the data is on the device. This can occur if the value was read on a previous application launch  or if the value was read by another application prior to this object observing.  

I am curious if this caused a problem though. The name `observer` is probably not the best choice either as it implies that many observers can be added. At the least the documentation should be clearer.

Thanks for the feedback.

**Comment by drdaz** [comment]
Oh... I had a suspicion that might be the case.

And it didn't cause a problem, but in my use case it's definitely not wanted. That's what forks are for I guess :)

Nice work on this btw. And really nice to see tests on libraries like this.

**Comment by KingOfBrian** [comment]
Let me think about how I might be able to accommodate the various use cases.  I'm guessing it involves real time data and the value at subscription is invalid?

And thanks! I'd love any feedback as to how things go from an application implementation or testing perspective. The testing side of things are pretty rough, but amazingly helpful. We were able to finish our implementation for a client without any hardware. Have you written a simulated device for your hardware? I apologize for the lack of documentation on that side.

Thanks!

**Comment by drdaz** [comment]
I guess you could say that my use case doesn't involve a BT device with a typical notifying characteristic... the peripheral relays inputs from a number of other simple devices (buttons actually) through a single characteristic. So any value that CB might have is entirely uninteresting... and it looked like a weird bug when initialising; a button press registered even though no buttons were being pressed :)

I've been trialling a number of similar libs over the past week or so... honestly the fact that it looks like some thorough testing has been done is a big plus. It means I have to be a little less concerned about testing all the way down to the CBPeripheral level, which I found out today is a PITA.

I haven't made a simulated device actually... and it would probably be pretty useful (depending on exactly what you mean).

No need to apologise!

**Pull request closed without merging**
