### PR TITLE
Option to get final callback before notify block is invalidated

### PR DESCRIPTION
**Pull request by felix-dumit**
This makes it so you can get one final callback when you subscribe to a characteristic's update when the subscription is canceled, or the device is disconnected.

I think there could be an argument for making this enabled by default, but for the sake of compatibility, I made it an opt-in property.

### CODE REVIEW

**Comment by KingOfBrian** [comment]
Hey @felix-dumit -- thanks for the PR. I've never had a device unsubscribe me before! I like using the error to notify this scenario, because it has limited API impact. I think this is a good default behavior to add, but can you some documentation to `enableNotify`? We can do a major version release to make sure we don't mess up any existing clients. 

I don't like the impact of triggering an error in all of the onUpdate blocks when a disconnect occurs though. For many use cases this will be very bit noisy. If you need to know about disconnection it might be best to handle it via the `connectionDelegate`. For instance, if I do some work on disconnect and am subscribed to 3 characteristics, I'll be notified with 3 errors and then the disconnection event. If this is horrible for your use case lets talk through some alternatives, but my default reaction is to hold off on this change.

Also, the current implementation will (I believe) also generate an error when a client calls `clearNotification...`, which I don't want to do. If the user invoked an API call it shouldn't result in an error.

Good catch, and thanks again for the PR

**Comment by KingOfBrian** [comment]
Hey @cpatterson-lilly -- do you have any thoughts on this scenario and how you'd like the library to behave?

**Comment by cpatterson-lilly** [comment]
I think I pretty much agree with your comments, @KingOfBrian.

The disconnect case can (and should) be handled by the `connectionDelegate`. Our code unsubscribes from a number of characteristics in that case.

Couldn't this case be handled by the standard `CBPeripheralDelegate - peripheral:didUpdateNotificationStateForCharacteristic:error:` method? Does that method get triggered when the peripheral changes the notify state already?

**Comment by KingOfBrian** [comment]
Yea, it triggers the delegate, RZBluetooth just drops it to the floor instead of exposing it to the client. One part of this PR transforms the notify=NO to an error.

(Also, I updated the travis config to fix the CI error)

**Comment by cpatterson-lilly** [comment]
Ah, I dug in a bit more; I see now. It gets dropped on the floor because there is no pending `RZBNotifyCharacteristicCommand` waiting for a response in that case.

I think, therefore, an improvement would be:
In `RZBCentralManager - peripheral:didUpdateNotificationStateForCharacteristic:error:`, 
only call the `setNotifyBlock:nil...` code if `completeFirstCommandOfClass:...` returns `false`. Otherwise, you're triggering `setNotifyBlock:nil` twice unnecessarily.

(And thanks for the travis fix!)

**Comment by felix-dumit** [comment]
Sorry for the delay in replying here, been a busy week.

Thanks for the feedback, I agree that notifying in the disconnected case might add too much noise.

Let me explain my use case a little bit, here is a simplified version of what I do:
```objc
-(BFTask<NSData*>*)waitForPeripheralToSendSomething:(RZBPeripheral*)peripheral {
    BFTaskCompletionSource* tcs = [BFTaskCompletionSource taskCompletionSource];
    
    [peripheral enableNotifyForCharacteristicUUID:uuid1 serviceUUID:uuid2 onUpdate:^(CBCharacteristic * _Nullable characteristic, NSError * _Nullable error) {
        if(error) {
            [tcs trySetError:error];
        } else {
            [tcs trySetResult:characteristic.value];
        }
    } completion:^(CBCharacteristic * _Nullable characteristic, NSError * _Nullable error) {
        if(error) {
            [tcs trySetError:error];
        }
    }];
    
    return tcs.task;
}
```

Without the notification on unsubscription, I'd have to maintain the state of all `BFTaskCompletionSource` somewhere else and then update it when the disconnect event happens (similarly if I had a completion block).  
It's not a huge issue, but I imagined a lot of people's workflow's would be similar and it would be nice to have a solution that didn't require the library's users to maintain extra state.

Maybe another alternative would be to have a method like `[peripheral listenForUnsubscribeToCharacteristic:service:block:]`?

I'm open to any other ideas.

**Comment by KingOfBrian** [comment]
Yea, I think we can remove the property if we only notify on disabling Notify. The other scenario to think of is if we want the error to be triggered when a user disables notification explicitly. I think it makes sense to do that too, just thinking it through.

For your use case, you should be able to use a subclass of RZPeripheral by specifying a `peripheralClass` when constructing RZCentralManager and encapsulating this behavior the same. I need to work on documenting and the 'Swifting' of the subclass behavior a bit more.

Also, can you update the formatting of the PR to match the rest of the app? In particular, else is uncuddled, a space after if/for, and method `{` are on the next line (in tests). Also can you add a `@note` to `enableNotifyForCharacteristicUUID` that describes the error behavior for the onUpdate block?

**Comment by felix-dumit** [comment]
I made the formatting changes.

On the error happening when the user disables the notification - I think it could be useful to have one final callback so you can do any cleanup after the subscription is terminated, that was my initial thinking with these changes.
But if we go down that route then I'd argue it would make sense for it to trigger on disconnect again (maybe with a different error). Because then it's alerting the user that he is disconnecting while he was still subscribed to characteristics.

Alternatively, we could move all this to another (optional) completion block that is called when the subscription is terminated indicating the final outcome: active unsubscribe, passive unsubscribe or disconnect.

**Pull request merged**
