### PR TITLE
Turning RZMockBluetooth into a framework

### PR DESCRIPTION
**Pull request by nickls**
Adding necessary components and project changes to make RZMockBluetooth build as a FW. This is helpful as it allows the FW to be included in projects without using pods and when using git submodules.

Also minor changes:

* Added `isScanning` to `RZBMockCentralManager`
* Added support for a named `RZBMockPeripheral`

Let me know if you would prefer these minor changes in their own PR.

### CODE REVIEW

**Comment by KingOfBrian** [comment]
Thanks a lot @nickls, it looks good! I was a bit unsure about `isScanning` since it looks like it's only a private ivar, and isn't exposed publicly looking at `CBCentralManager.h`, but I see no harm in adding it. Out of curiosity, why do you need it?

I have to check out the framework changes, but should be able to merge soon. One small nit-pick is the indentation on the `peripheralName:` tags is off.

**Comment by nickls** [comment]
It is used in some of the legacy code I built tests for -- knowing when to restart the scanning.

I just checked `CBCentralManager.h` and it is available there and isn't market private am I missing something?
```
@property(nonatomic, assign, readonly) BOOL isScanning NS_AVAILABLE(NA, 9_0);
```

**Comment by nickls** [comment]
Just fixed the indentation issue, good call that was ugly. :-D

Thanks for making such a great library.

**Comment by cpatterson-lilly** [comment]
@nickls Just curious, if I'm already using RZBMockBluetooth via CocoaPods, will this change how I use it in my test targets?

**Comment by cpatterson-lilly** [comment]
@nickls Why append the word "Kit" to the framework? "RZBMockBluetooth" is unique enough on its own, matches the existing umbrella header, and the main framework does not use that suffix.

**Comment by nickls** [comment]
no people can continue to use RZBMockBluetooth via CocoaPods as they always have.

@cpatterson-lilly I was trying to follow convention and to make sure it was obviously a different target in the dropdown. Happy to drop the kit if you would prefer.

**Comment by KingOfBrian** [comment]
Yea, I'd prefer to drop `Kit` to keep the naming consistent. Sorry for the delay here, the PR is much appreciated!

**Comment by Soulphalanx** [comment]
Can the framework scheme be shared so it's compatible with Carthage as well?

**Comment by nickls** [comment]
I've renamed the framework as requested and built it using Carthage to test.

Let me know if you want to see any other changes. Thanks again for making this!

**Comment by KingOfBrian** [comment]
Hey @nickls , sorry for the delay, was sick all week. Any chance you could make a PR of just the framework changes? 

Also, looking at the name change, I think I'd rather expose the `RZBMockPeripheral *peripheral` on the `RZBSimulatedConnection` for configuration rather than pass in configuration options. This would allow:
ie:
```objc
RZBSimulatedConnection *connection = [simCentral connectionForIdentifier:uuid];
connection.peripheral.name = @"My Name";
connection.peripheral.RSSI = @88;
```

Sorry for the late-breaking opinion on this, I just think it will be a bit more useful for default RSSI configuration.

**Pull request merged**
