### PR TITLE
Fixes for issue #64

### PR DESCRIPTION
**Pull request by cpatterson-lilly**
- Added service UUID parameter to `RZBSimulatedDevice` callback methods.
- Built a string key from characteristic and service UUIDs for internal `RZBSimulatedDevice` handler dictionaries.
- Added unit test.

### CODE REVIEW

**Comment by KingOfBrian** [comment]
Hey @cpatterson-lilly -- This looks great. I'd really like to maintain compatibility on `RZBSimulatedDevice` with the callback methods though. Part of me wants to ditch compatibility because of the additional 6 methods it will require, but I think letting people upgrade with out breaking changes is more important.

**Comment by cpatterson-lilly** [comment]
@KingOfBrian Yeah, I understand the desire to avoid changing the API. Especially, in this case, which is pretty much an edge case.

I'll add back the original API calls that don't have a service UUID parameter, and those calls will search for the correct service UUID to use. If they find a single match (the usual case), all is well. 

What should they do if they find multiple matches? Fail via assertion, throw an exception, or just return the first (possibly incorrect) match?

**Comment by KingOfBrian** [comment]
I think you can look up specifically (cUUID,sUUID) then generically (cUUID)
you should be good. I'm not sure that I see a special error case from there.

**Comment by cpatterson-lilly** [comment]
@KingOfBrian I'm asking about the case where you try to add a handler to an `RZBSimulatedDevice` by characteristic UUID alone, and it finds the same cUUID on multiple services -- what should the API do? 
 - Throw an assertion failure (let the developer know about the conflict), or
 - Just add the handler for the first matching (cUUID, sUUID) it finds (which may cause tests to fail).

I'm leaning towards throwing the assertion failure; as a unit test developer I want to know about the problem sooner rather than later.

**Comment by KingOfBrian** [comment]
I was thinking that it wouldn't care, but I can see the argument for being
a bit cautious about it. I'd be cool with adding an assert to protect that
scenario. Sometimes I'll do exceptions over asserts to make sure they don't
get disabled, but either would work for me.

**Comment by KingOfBrian** [comment]
Ok, one last request @cpatterson-lilly -- can you revert the changes to the tests that aren't needed so both code paths are covered?

**Comment by cpatterson-lilly** [comment]
Will do.

**Comment by cpatterson-lilly** [comment]
@KingOfBrian Would you want to mark the original API methods deprecated, using `__deprecated` or `__attribute__((deprecated))` or `__attribute__((deprecated("message")))`?

**Comment by KingOfBrian** [comment]
Looks great @cpatterson-lilly -- I owe you a 🍺. It won't be at this WW unfortunately, but someday!

**Comment by cpatterson-lilly** [comment]
Awwwww... someday for sure!

**Pull request merged**
